import React, { useEffect, useState } from "react";
import OverviewTab from "./components/OverviewTab";
import ExperimentDesignTab from "./components/ExperimentDesignTab";
import AiTab from "./components/AiTab";
import AboutTab from "./components/AboutTab";
import WhatIfTab from "./components/WhatIfTab";

const API_BASE = (import.meta.env.VITE_API_BASE ?? "http://localhost:8000").replace(/\/$/, "");
const tabs = ["Overview", "Experiment Design", "What If", "AI Message Review", "About"];
const overviewUrl = `${API_BASE}/api/overview`;
const aiRecommendationUrl = `${API_BASE}/api/ai/recommendation`;

export default function App() {
  const [activeTab, setActiveTab] = useState("Overview");
  const [overview, setOverview] = useState(null);
  const [aiRecommendation, setAiRecommendation] = useState(null);
  const [error, setError] = useState("");
  const [showBriefing, setShowBriefing] = useState(true);

  useEffect(() => {
    fetchJson(overviewUrl, "overview metrics").then(setOverview).catch((err) => setError(err.message));
    fetchJson(aiRecommendationUrl, "AI recommendation")
      .then(setAiRecommendation)
      .catch((err) => setError(err.message));
  }, []);

  return (
    <main className="app-shell">
      <header className="hero">
        <div>
          <p className="eyebrow">Turnout intervention control room</p>
          <h1>Adaptive Ballot Chase</h1>
          <p>
            Prioritize voters who requested mail ballots but may need the right reminder to return them.
            This live demo compresses a longer ballot chase program into a short simulation so viewers can watch
            allocation, confidence, and returned-ballot impact update over time.
          </p>
        </div>
        <div className="hero-card">
          <span>Hero metric</span>
          <strong className="hero-primary-metric">
            Estimated additional returned ballots
            <span className="hero-help-wrap">
              <button aria-label="Primary metric help" className="help-icon" type="button">?</button>
              <span className="tooltip-popover hero-tooltip" role="tooltip">
                Estimated additional returned ballots generated by adaptive outreach compared to the current chase policy baseline. This estimates the incremental turnout impact from changing intervention allocation.
              </span>
            </span>
          </strong>
          <small>Secondary metrics: ballot return rate, average uplift, contact fatigue risk, and traffic allocation.</small>
          <div className={overview ? "hero-live-status ready" : "hero-live-status"}>
            <strong>{overview ? "Live data ready" : "Loading simulated campaign results, usually 10-15 seconds"}</strong>
            <span>
              This dashboard compares ballot chase allocation strategies, tracks whether adaptive methods beat Control,
              and keeps confidence/readiness visible for leadership.
            </span>
            <button className="briefing-button" onClick={() => setShowBriefing(true)} type="button">Project briefing</button>
          </div>
        </div>
      </header>

      <section className="benchmark-strip" aria-label="Research and industry grounding">
        <article>
          <span>Yahoo/LinUCB contextual bandit</span>
          <strong>12.5% click lift</strong>
          <p>over non-contextual baseline</p>
        </article>
        <article>
          <span>Spotify contextual bandits</span>
          <strong>&gt;25% improvement</strong>
          <p>in expected stream rate from improved reward definitions</p>
        </article>
        <article>
          <span>Optimizely contextual bandits</span>
          <strong>13.62% higher engagement</strong>
          <p>and 20.79% validation improvement</p>
        </article>
      </section>

      {showBriefing && (
        <section className="briefing-overlay" onClick={() => setShowBriefing(false)} role="dialog" aria-modal="true" aria-labelledby="briefing-title">
          <div className="briefing-panel" onClick={(event) => event.stopPropagation()}>
            <div className="briefing-head">
              <p className="eyebrow">Executive briefing</p>
              <h2 id="briefing-title">Adaptive ballot chase simulation</h2>
              <p>
                This live demo explores how adaptive experimentation could reshape ballot chase programs. A voter has already requested a mail ballot, but the campaign still needs to help ensure it is returned. Contextual bandits continuously learn which voters are movable, which intervention is most useful, and when contact fatigue makes suppression the better choice.
              </p>
              <p>
                The goal is not to chase every outstanding ballot equally. The goal is to identify where contact is most likely to change behavior while preserving capacity, monitoring fatigue, and keeping human review in the loop.
              </p>
            </div>
            <div className="briefing-actions">
              <button className={overview ? "ready-action" : ""} onClick={() => setShowBriefing(false)} type="button">
                {overview ? "Live data ready" : "Skip intro"}
              </button>
            </div>
          </div>
        </section>
      )}

      <nav className="tabs" aria-label="Dashboard tabs">
        {tabs.map((tab) => (
          <button
            className={activeTab === tab ? "active" : ""}
            key={tab}
            onClick={() => setActiveTab(tab)}
            type="button"
          >
            {tab}
          </button>
        ))}
      </nav>

      {error && <div className="alert">{error}</div>}
      {activeTab === "Overview" && <OverviewTab overview={overview} />}
      {activeTab === "Experiment Design" && <ExperimentDesignTab />}
      {activeTab === "What If" && <WhatIfTab apiBase={API_BASE} />}
      {activeTab === "AI Message Review" && <AiTab recommendation={aiRecommendation} overview={overview} />}
      {activeTab === "About" && <AboutTab />}
    </main>
  );
}

async function fetchJson(url, label) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Unable to load ${label} from ${url} (${response.status}).`);
  }
  return response.json();
}
